spring:
  application:
    name: greeting-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

greeting-service:
  greeting: "Mundo"
  default-value: "Olá"
